// Generated by CoffeeScript 1.9.3
(function() {
  var ServeStatic, connect;

  connect = require('connect');

  ServeStatic = require('serve-static');

  connect().use(ServeStatic(__dirname)).listen(8080);

}).call(this);

//# sourceMappingURL=server.js.map
