// Generated by CoffeeScript 1.9.3
(function() {
  describe('Temperature Converter for', function() {
    var centigradeSymbol, converter, fahrenheitSymbol, runs;
    runs = [
      {
        fahrenheit: '10.00',
        centigrade: '-12.22'
      }, {
        fahrenheit: '50.00',
        centigrade: '10.00'
      }, {
        fahrenheit: '100.00',
        centigrade: '37.78'
      }, {
        fahrenheit: '0.00',
        centigrade: '-17.78'
      }, {
        fahrenheit: '32.00',
        centigrade: '0.00'
      }
    ];
    converter = new TemperatureConverter;
    fahrenheitSymbol = converter.fahrenheitSymbol();
    centigradeSymbol = converter.centigradeSymbol();
    describe("Fahrenheit to Centigrade", function() {
      var typeOfConversion;
      typeOfConversion = '1';
      return runs.forEach(function(run) {
        return it("converts " + run.fahrenheit + " " + fahrenheitSymbol + " to " + run.centigrade + " " + centigradeSymbol, function() {
          var result;
          result = converter.convert(typeOfConversion, run.fahrenheit);
          return expect(result).toBe(run.centigrade + " " + centigradeSymbol);
        });
      });
    });
    return describe("Centigrade to Fahrenheit", function() {
      var typeOfConversion;
      typeOfConversion = '2';
      return runs.forEach(function(run) {
        return it("converts " + run.centigrade + " " + centigradeSymbol + " to " + run.fahrenheit + " " + fahrenheitSymbol, function() {
          var result;
          result = converter.convert(typeOfConversion, run.centigrade);
          return expect(result).toBe(run.fahrenheit + " " + fahrenheitSymbol);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=fahrenheit.spec.js.map
