// Generated by CoffeeScript 1.9.3
(function() {
  describe("Finding words in a text", function() {
    var runs;
    runs = [
      {
        word: 'a',
        text: 'a b c d a',
        result: 2
      }, {
        word: 'z',
        text: 'a b c d a',
        result: 0
      }, {
        word: 'A',
        text: 'a b c d a',
        result: 0
      }, {
        word: '',
        text: 'a b c d a',
        result: 0
      }, {
        word: 'ab',
        text: 'a b c dab ab',
        result: 2
      }, {
        word: '1',
        text: '101010101',
        result: 5
      }, {
        word: '1',
        text: '',
        result: 0
      }
    ];
    return runs.forEach(function(run) {
      return it("finds " + run.result + " occurrences of '" + run.word + "' in '" + run.text + "'", function() {
        var result;
        result = countWord(run.word, run.text);
        return expect(result).toBe(run.result);
      });
    });
  });

}).call(this);

//# sourceMappingURL=findings.spec.js.map
