// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var countWord, search;

  countWord = function(word, input) {
    var isFound, position, wordCount;
    if (!word) {
      return 0;
    }
    position = 0;
    wordCount = 0;
    isFound = function(position) {
      return position !== -1;
    };
    while (isFound(position)) {
      position = input.indexOf(word, position);
      if (isFound(position)) {
        wordCount++;
        position++;
      }
    }
    return wordCount;
  };

  window.countWord = countWord;

  search = function() {
    var $text, input, word, wordCount;
    $text = $('#text');
    $text.unhighlight();
    input = $text.html().trim();
    word = $('#searchTextBox').val();
    wordCount = word != null ? countWord(word, input) : 0;
    $text.highlight(word);
    return $('#result').text("There are " + wordCount + " occurrences of the word " + word + ".");
  };

  $('#searchTextBox').val('in');

  $('form').on('input', search).trigger('input');

}).call(this);

//# sourceMappingURL=findings.js.map
